"""LLM-as-judge via Anthropic Claude (independent from Gemini pathway generator)."""

from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

from lib.personalization_prompt import SURVEY_QUESTIONS, format_block_catalog, load_generation_spec
from lib.rate_limit import api_delay_sec, call_with_rate_limit_retry
from lib.research_metrics import block_multiset, block_sequence

STUDY_ROOT = Path(__file__).resolve().parent.parent

JUDGE_TOOL = {
    "name": "score_pathway_personalization",
    "description": "Score how well a pathway structurally matches a learner profile",
    "input_schema": {
        "type": "object",
        "properties": {
            "scores": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "dimension_id": {"type": "string"},
                        "score": {"type": "number"},
                        "justification": {"type": "string"},
                    },
                    "required": ["dimension_id", "score", "justification"],
                },
            },
            "overall_comment": {"type": "string"},
            "is_structural_not_cosmetic": {"type": "boolean"},
        },
        "required": ["scores", "overall_comment", "is_structural_not_cosmetic"],
    },
}


def _load_env() -> None:
    load_dotenv(STUDY_ROOT / ".env")
    root_env = STUDY_ROOT.parent / ".env"
    if root_env.exists():
        load_dotenv(root_env, override=False)


def get_anthropic_client() -> Any:
    _load_env()
    api_key = os.getenv("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        raise ValueError(
            "ANTHROPIC_API_KEY not set in study/.env or repo root .env — required for LLM judge"
        )
    import anthropic

    return anthropic.Anthropic(api_key=api_key)


def get_claude_judge_model() -> str:
    _load_env()
    return os.getenv("CLAUDE_JUDGE_MODEL", "claude-sonnet-4-6").strip()


def _format_profile(answers: dict[str, str]) -> str:
    lines = [f"Q: {q['text']}\nA: {answers.get(q['id'], '')}" for q in SURVEY_QUESTIONS]
    return "\n".join(lines)


def _format_pathway(nodes: list[dict[str, Any]]) -> str:
    lines = []
    for i, n in enumerate(nodes, 1):
        lines.append(
            f"{i}. [{n.get('syllabusBlockId', '?')}] {n.get('title')} "
            f"({n.get('difficulty')}, {n.get('type')}) — {n.get('description', '')[:200]}"
        )
    return "\n".join(lines)


def judge_pathway(
    client: Any,
    profile_id: str,
    profile_description: str,
    answers: dict[str, str],
    nodes: list[dict[str, Any]],
    syllabus: dict[str, Any],
    *,
    model: str | None = None,
    spec_path: Path | None = None,
) -> dict[str, Any]:
    spec = load_generation_spec(spec_path)
    rubric = spec.get("judgeRubric", {})
    dimensions = rubric.get("dimensions", [])
    dim_text = "\n".join(f"- {d['id']}: {d['description']}" for d in dimensions)
    scale = rubric.get("scale", {"min": 1, "max": 5})

    block_summary = {
        "sequence": block_sequence(nodes),
        "counts": dict(block_multiset(nodes)),
    }

    prompt = f"""You are an independent expert reviewer for an adaptive learning systems research paper.
The pathway was generated by a different model (Google Gemini). Your job is to evaluate structural personalization objectively.

IMPORTANT:
- Use the full {scale['min']}-{scale['max']} scale honestly. Score 5 only for excellent alignment. Score 1 for clear mismatch.
- Penalize cosmetic-only personalization (same block coverage with reworded titles).
- Do not inflate scores to be agreeable.

=== LEARNER PROFILE ({profile_id}) ===
{profile_description}

{_format_profile(answers)}

=== SYLLABUS BLOCK CATALOG ===
{format_block_catalog(spec, syllabus)}

=== GENERATED PATHWAY ===
Block sequence (derived): {block_summary['sequence']}
Block node counts: {block_summary['counts']}

Nodes:
{_format_pathway(nodes)}

=== RUBRIC DIMENSIONS ===
{dim_text}

Score each dimension {scale['min']}-{scale['max']} with a one-sentence justification.
Set is_structural_not_cosmetic to true ONLY if block coverage/order reflects the profile meaningfully."""

    model_name = model or get_claude_judge_model()

    def _call() -> Any:
        response = client.messages.create(
            model=model_name,
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
            tools=[JUDGE_TOOL],
            tool_choice={"type": "tool", "name": "score_pathway_personalization"},
        )
        tool_block = next(
            (block for block in response.content if block.type == "tool_use"),
            None,
        )
        if tool_block is None:
            raise RuntimeError(f"Claude judge returned no tool use for {profile_id}")
        result = tool_block.input
        if not isinstance(result, dict):
            raise RuntimeError("Invalid judge response")
        return result

    result = call_with_rate_limit_retry(_call, label=f"Claude judge ({profile_id})")

    scores = result.get("scores", [])
    numeric = [s["score"] for s in scores if isinstance(s.get("score"), (int, float))]
    mean_score = sum(numeric) / len(numeric) if numeric else 0.0

    return {
        "profileId": profile_id,
        "judge_model": model_name,
        "judge_provider": "anthropic",
        "scores": scores,
        "mean_score": round(mean_score, 3),
        "overall_comment": result.get("overall_comment", ""),
        "is_structural_not_cosmetic": result.get("is_structural_not_cosmetic", False),
    }


def judge_all_profiles(
    client: Any,
    profiles: list[dict[str, Any]],
    pathways_dir_data: dict[str, list[dict[str, Any]]],
    syllabus: dict[str, Any],
    *,
    profile_ids: list[str] | None = None,
    delay_sec: float | None = None,
    spec_path: Path | None = None,
) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    selected = profiles
    if profile_ids is not None:
        allowed = set(profile_ids)
        selected = [p for p in profiles if p["id"] in allowed]

    for profile in selected:
        pid = profile["id"]
        if pid not in pathways_dir_data:
            continue
        print(f"  Judging {pid} (Claude)...")
        results.append(
            judge_pathway(
                client,
                pid,
                profile.get("description", ""),
                profile["answers"],
                pathways_dir_data[pid],
                syllabus,
                spec_path=spec_path,
            )
        )
        time.sleep(delay_sec if delay_sec is not None else api_delay_sec())
    return results


DEFAULT_CANONICAL_IDS = {
    "low_knowledge_general",
    "high_knowledge_research",
    "business_leader",
    "ethics_focused",
    "medium_knowledge_mixed",
    "learning_style_control",
}


def stratified_judge_sample(
    profiles: list[dict[str, Any]],
    sample_size: int,
    *,
    canonical_ids: set[str] | None = None,
) -> list[str]:
    """Pick up to sample_size profiles: canonical anchors + at least one per cluster.

    `canonical_ids` defaults to the AI-literacy anchor set; pass a course-specific
    set for other courses (their anchor ids won't exist in the default set)."""
    canonical = canonical_ids if canonical_ids is not None else DEFAULT_CANONICAL_IDS
    chosen: list[str] = []
    seen_clusters: set[str] = set()

    for p in profiles:
        if p["id"] in canonical and p["id"] not in chosen:
            chosen.append(p["id"])
            seen_clusters.add(p.get("cluster", ""))

    for p in profiles:
        cluster = p.get("cluster", "")
        if cluster in seen_clusters:
            continue
        chosen.append(p["id"])
        seen_clusters.add(cluster)
        if len(chosen) >= sample_size:
            return chosen[:sample_size]

    for p in profiles:
        if p["id"] not in chosen:
            chosen.append(p["id"])
        if len(chosen) >= sample_size:
            break
    return chosen[:sample_size]
